### ISSUE TITLE
Is there any situation that make sendPacket return error when resolve a request?

### ISSUE THREAD

**Issue by taobun** [bandprotocol/chain#112]
https://github.com/bandprotocol/chain/blob/master/x/oracle/keeper/result.go#L139

If `SendPacket` return error (might be from the channel has been closed before the request resolved), and what happen if this happen?

## Possible fix
- Disable closing channel confirmation
- Dont' panic on SendPacket function

**Comment by songwongtp** [comment]
make a WARNING in a relayer doc that closing a channel can make them lose their request pool

**Comment by taobun** [comment]
Let create the issue on relayer repo
