### ISSUE TITLE
Ability to delegate oracle re-activation to another account

### ISSUE THREAD

**Issue by joe-bowman** [bandprotocol/chain#182]
Given the propensity for the band oracle to deactivate if the wind blows in the wrong direction, we end up running `bandcli tx oracle activate` on a semi regularly basis (once or twice a month). 

Given proper key handling, our platforms team do not have the ability to reactivate the oracle - as this requires possesion of the key that controls the entire validator (including the ability to withdraw / send funds, etc.)

It would be hugely beneficial, if in the next iteration, if the validator account could sign a tx to (optionally) authorise a separate sub account (with no other permissions), that could re-enable the oracle in the event of a failure (much like Terra delegates permission to their oracle feeder account).

**Comment by taobun** [comment]
In this `bandd` version, our chain adds new `authz` module that allows other addresses to send specific msg for the main account. 

What you need to do:
1. Send `MsgGrant` for your validator key to allow some address to send `MsgActivate` for validator account.
2. When you want to activate your oracle, you need to send `ExecMsg` that contains `MsgActivate` and sent by sub-account address.
