### ISSUE TITLE
Can not use txs/encode api for encodeTx

### ISSUE THREAD

**Issue by Wangmmx** [bandprotocol/chain#194]
Hi, is there a big upgrade for band?

I used to encode tx using this api `txs/encode` and sent it successfully in testnet2 and guanyu-mainnet
But it got error when in laozi mainnet and I did not change anything
The api returned this error:
```{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}
```
How can I use the txs/encode now? I need to build tx body offline and use rest api to send, looking forward to your reply

**Comment by Wangmmx** [comment]
?

**Comment by taobun** [comment]
@Wangmmx Cosmos-sdk removed legacy encode and broadcast tx endpoint for vulnerable issues. Please use protobuf to encode tx instead. Comsmos docs: https://docs.cosmos.network/v0.44/migrations/rest.html
