### ISSUE TITLE
How to deploy a full node?

### ISSUE THREAD

**Issue by bladehan1** [bandprotocol/chain#208]
Where is the document?

**Comment by RogerKSI** [comment]
Hi, sorry for the late reply.
For testnet5, you can use [https://github.com/bandprotocol/launch/tree/master/band-laozi-testnet5](https://github.com/bandprotocol/launch/tree/master/band-laozi-testnet5).
For mainnet, you can use [https://github.com/bandprotocol/chain/wiki/BandChain-Laozi-Mainnet:-How-to-Join-as-a-Validator](https://github.com/bandprotocol/chain/wiki/BandChain-Laozi-Mainnet:-How-to-Join-as-a-Validator).
