### ISSUE TITLE
[Question] Where may I find the source code of the standard dataset oracle script?

### ISSUE THREAD

**Issue by ImJeremyHe** [bandprotocol/chain#316]
Hi!
I am learning how to write oracle scripts and as references I am looking for the source code of the
[Cryptocurrency Standard Dataset
](https://www.cosmoscan.io/oracle-script/3) please tell me where to find this code.
Thank you very much!

**Comment by RogerKSI** [comment]
@ImJeremyHe Hi, You can see the code at the OWASM Code tab on the page. It might take time a bit for loading.
https://www.cosmoscan.io/oracle-script/3#code

**Comment by ImJeremyHe** [comment]
@RogerKSI Thank you! Would you show me where can I find the code implementing `oei::ask_external_data`?  How the validators know where they should fetch the data?

**Comment by RogerKSI** [comment]
@ImJeremyHe Hi, please find my answers below:

1. Would you show me where can I find the code implementing oei::ask_external_data?
for the implementation of oei::ask_external_data, you can find it [here](https://github.com/bandprotocol/owasm/blob/master/packages/kit/src/oei/mod.rs). 
However, it will callback to go-owasm [here](https://github.com/bandprotocol/go-owasm/blob/master/libgo_owasm/src/vm.rs) and chain [here](https://github.com/bandprotocol/chain/blob/master/x/oracle/types/exec_env.go).

2. How do the validators know where they should fetch the data?
Briefly, when the oracle script calls ask_external_data, the chain will emit events that contain information (e.g. data sources, validators, calldata). Yoda (the program that validators need to run to be Oracle providers) will monitor those events and fetch the data according to that information.

**Comment by ImJeremyHe** [comment]
@RogerKSI Thank you! That's what I want!
