### ISSUE TITLE
About usage of floating point in the oracle script

### ISSUE THREAD

**Issue by zicofish** [bandprotocol/chain#397]
Hi, while reading the documentation, I found the usage of f64 in the following oracle script example:

https://docs.bandchain.org/core-concepts/oracle-webassembly

You mentioned that your script is run on-chain instead of off-chain, but Cosmos cosmwasm doesn't support floating points because they are not safe. So I was wondering what's the trick with Owasm? Is the script really run on chain, or there might be misunderstanding of concepts from my side?

**Comment by RogerKSI** [comment]
Yes, the script is run on the chain. However, Owasm lies in the execution environment provided by Wasmer, specifically using the singlepass compiler backend. Wasmer's singlepass backend ensures that floating-point operations are handled deterministically. This means all validators will produce the same results when executing the same floating-point operations. You can find more details here (https://github.com/wasmerio/wasmer/issues/1269).
